export const fonts: { name: string; slug: string }[] = [
  { name: "Aesthetic Beauty", slug: "aesthetic_beauty" },
  { name: "BabelSans", slug: "babelsans" },
  { name: "BebasNeue-Regular", slug: "bebasneue_regular" },
  { name: "Benedict Sans Regular", slug: "benedict_sans_regular" },
  { name: "Birds of Paradise", slug: "birds_of_paradise" },
  { name: "CaviarDreams", slug: "caviardreams" },
  { name: "Classyvogueregular", slug: "classyvogueregular" },
  { name: "Comfortaa-Regular", slug: "comfortaa_regular" },
  { name: "CreatoDisplay-Regular", slug: "creatodisplay_regular" },
  { name: "Draken", slug: "draken" },
  { name: "Frenstyle", slug: "frenstyle" },
  { name: "Galvanizer-Regular", slug: "galvanizer_regular" },
  { name: "KingSans-FREE", slug: "kingsans_free" },
  { name: "LEMONMILK-Regular", slug: "lemonmilk_regular" },
  { name: "Louis George Cafe", slug: "louis_george_cafe" },
  { name: "Madina", slug: "madina" },
  { name: "Roboto-Regular", slug: "roboto_regular" },
  { name: "Simple Michael", slug: "simple_michael" },
  { name: "Smith Buck", slug: "smith_buck" },
  { name: "TangoSans", slug: "tangosans" },
  { name: "TheNextFont", slug: "thenextfont" },
];
